# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgpx.proto\x12\x03gpx\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n\x07Workout\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x04meta\x18\x03 \x03(\x0b\x32\x16.gpx.Workout.MetaEntry\x12\x18\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\n.gpx.Point\x12\x0f\n\x07\x65lapsed\x18\x05 \x01(\x05\x12\x16\n\x0etotal_distance\x18\x06 \x01(\x05\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8a\x01\n\x05Point\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x11\n\televation\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\x10\n\x08\x64istance\x18\x06 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKOUT_METAENTRY._options = None
  _WORKOUT_METAENTRY._serialized_options = b'8\001'
  _WORKOUT._serialized_start=52
  _WORKOUT._serialized_end=267
  _WORKOUT_METAENTRY._serialized_start=224
  _WORKOUT_METAENTRY._serialized_end=267
  _POINT._serialized_start=270
  _POINT._serialized_end=408
# @@protoc_insertion_point(module_scope)
